--COLUMN CATCHER
			DECLARE @column_name NVARCHAR(50)
			DECLARE @ROWNUMB2 INT
			DECLARE @DATATYPE NVARCHAR(20)
			DECLARE @tn2  NVARCHAR(20)
			DECLARE @DATATYPE_LENGTH INT
			DECLARE CURSOR_columns CURSOR 
			FOR
			SELECT  TABLE_NAME,COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH
			FROM INFORMATION_SCHEMA.COLUMNS
			WHERE(COLUMN_DEFAULT IS NULL ) AND COLUMN_NAME NOT LIKE '%ID%' 
						OPEN CURSOR_columns

			FETCH NEXT FROM CURSOR_columns
			INTO @ROWNUMB2, @column_name,@DATATYPE,@tn2,@DATATYPE_LENGTH

			WHILE @@FETCH_STATUS=0
			BEGIN

			FETCH NEXT FROM CURSOR_columns
			INTO @ROWNUMB2,@column_name,@DATATYPE,@tn2,@DATATYPE_LENGTH

			

			END
			CLOSE CURSOR_columns
			DEALLOCATE CURSOR_columns
