			--ID  catcher
			DECLARE @RowNumb INT
			DECLARE @TableName NVARCHAR(20)
			DECLARE ROWNUMBCURS CURSOR
			FOR
				SELECT ROW_NUMBER()over (PARTITION BY S.TABLE_NAME ORDER BY S.TABLE_NAME) ,S.TABLE_NAME
			    FROM INFORMATION_SCHEMA.TABLES S
				INNER JOIN INFORMATION_SCHEMA.COLUMNS P
				ON S.TABLE_NAME=P.TABLE_NAME
				WHERE TABLE_TYPE  LIKE 'BASE TABLE' AND P.COLUMN_NAME LIKE '%ID' AND P.COLUMN_NAME NOT LIKE 'rowguid' 

				OPEN ROWNUMBCURS
				FETCH NEXT FROM ROWNUMBCURS
				INTO @RowNumb,@TableName
				
				WHILE @@FETCH_STATUS=0
				BEGIN
								FETCH NEXT FROM ROWNUMBCURS
								INTO @RowNumb,@TableName
				
								IF @RowNumb=1
								BEGIN
								
								PRINT @RowNumb
								PRINT @TableName
								END
				END
				CLOSE ROWNUMBCURS
				DEALLOCATE ROWNUMBCURS
