--TEST
DECLARE @TableFullName NVARCHAR(100)
DECLARE @TableName NVARCHAR(100)
DECLARE tables_cursor CURSOR
FOR
SELECT TABLE_NAME 'TableName',TABLE_SCHEMA + '.' + TABLE_NAME 'TableFullName'
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'

OPEN tables_cursor

FETCH NEXT FROM tables_cursor
INTO @TableName,@TableFullName




WHILE @@FETCH_STATUS = 0
BEGIN
			DECLARE @column_name NVARCHAR(50)
			DECLARE @ROWNUMB2 NVARCHAR(20)
			DECLARE @DATATYPE NVARCHAR(20)
			
			DECLARE @DATATYPE_LENGTH INT
			DECLARE CURSOR_columns CURSOR 
			FOR
			SELECT  TABLE_NAME,COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH
			FROM INFORMATION_SCHEMA.COLUMNS
			WHERE(COLUMN_DEFAULT IS NULL ) AND COLUMN_NAME NOT LIKE '%ID%' 
			OPEN CURSOR_columns

			FETCH NEXT FROM CURSOR_columns
			INTO @ROWNUMB2, @column_name,@DATATYPE,@DATATYPE_LENGTH

			WHILE @@FETCH_STATUS=0
			BEGIN
			PRINT @COLUMN_NAME
			FETCH NEXT FROM CURSOR_columns
			INTO @ROWNUMB2,@column_name,@DATATYPE,@DATATYPE_LENGTH
			
						--DECLARE @RowNumb INT
						--DECLARE @COLUMN_NAME_ID NVARCHAR(20)
						--DECLARE @tn nvarchar(20)
						--DECLARE ROWNUMBCURS CURSOR
						--FOR
						--SELECT ROW_NUMBER()over (PARTITION BY S.TABLE_NAME ORDER BY S.TABLE_NAME) ,s.TABLE_NAME,P.COLUMN_NAME
						--FROM INFORMATION_SCHEMA.TABLES S
						--INNER JOIN INFORMATION_SCHEMA.COLUMNS P
						--ON S.TABLE_NAME=P.TABLE_NAME
						--WHERE TABLE_TYPE  LIKE 'BASE TABLE' AND P.COLUMN_NAME LIKE '%ID' AND P.COLUMN_NAME NOT LIKE 'rowguid' 

						--OPEN ROWNUMBCURS
						--FETCH NEXT FROM ROWNUMBCURS
						--INTO @RowNumb,@tn,@COLUMN_NAME_ID
				
						--WHILE @@FETCH_STATUS=0
						--BEGIN

						--FETCH NEXT FROM ROWNUMBCURS
						--INTO @RowNumb,@tn,@COLUMN_NAME_ID

						--IF @RowNumb=1 AND @tn=@TableName AND  @tn2=@TableName
						--BEGIN
						--PRINT CONCAT('USD_UPDATE_',@TABLEFULLNAME,'(',@COLUMN_NAME_ID,')','BEGIN','	',@COLUMN_NAME)
						--END

						--END
						--CLOSE ROWNUMBCURS
						--DEALLOCATE ROWNUMBCURS


			END
			CLOSE CURSOR_columns
			DEALLOCATE CURSOR_columns
FETCH NEXT FROM tables_cursor
INTO @TableName,@TableFullName

END
CLOSE tables_cursor
DEALLOCATE tables_cursor
